import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import org.junit.Test;
import org.sportradar.constants.Constants;
import org.sportradar.models.Match;
import org.sportradar.models.Team;

public class MatchTest {

  @Test
  public void testMatchConstructor() {
    var match = new Match("Spain", "USA");
    assertEquals("Spain", match.getHomeTeam().getName());
    assertEquals("USA", match.getAwayTeam().getName());
    assertEquals(Team.class, match.getHomeTeam().getClass());
    assertEquals(Team.class, match.getAwayTeam().getClass());
    // Autogenerated IDs starts at 1
    assertTrue(match.getId() > Constants.ZERO);
  }

  @Test
  public void TestToString() {
    var match = new Match("Spain", "USA");
    assertEquals("Spain 0 - 0 USA", match.toString());
  }

}
